[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["romann"]
include-package-data = true

[tool.setuptools.package-data]
romann = ["hiragana_english.json", "katakana_english.json"]
