name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Clean existing installation directory
      run: |
        if [ -d "./src/romann" ]; then
          rm -rf ./src/romann
        fi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . --no-input
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt --no-input; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')